# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  ARM_PASS: $(adminPass)

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: CopyFile
  jobs: 
  - job: CopyFile
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'quickstarts/microsoft.web/webapp-linux-managed-mysql/'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

- stage: Deployement
  dependsOn:
  - CopyFile
  jobs: 
  - job: Deployement
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Azure Internal Sub'
        subscriptionId: '9e6911a6-e33a-428c-9337-a0b3d70f17b2'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'ARMPipelinesLAMP-rg'
        location: 'Japan East'
        templateLocation: 'Linked artifact'
        csmFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.json'
        csmParametersFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.parameters.json'
        overrideParameters: '-siteName $(siteName) -administratorLogin $(adminUser) -administratorLoginPassword $(ARM_PASS)'
        deploymentMode: 'Incremental'

- stage: DeleteResource
  dependsOn:
  - Deployement
  jobs: 
  - job: Deployement
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Azure Internal Sub'
        subscriptionId: '9e6911a6-e33a-428c-9337-a0b3d70f17b2'
        action: 'DeleteRG'
        resourceGroupName: 'ARMPipelinesLAMP-rg'
        location: 'Japan East'